package com.hospital.platform.audit.contract;

public enum AuditEventType {
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CHECKED_IN,
    APPOINTMENT_WAITING,
    APPOINTMENT_ATTENTION_STARTED,
    APPOINTMENT_COMPLETED
}
